"""Removed id column from application user

Revision ID: 01d5a3667eed
Revises: bc3b1fb31cae
Create Date: 2021-11-05 22:45:03.271732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01d5a3667eed'
down_revision = 'bc3b1fb31cae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
