"""date_of_birth column added

Revision ID: 3a3fe14c17b2
Revises: bdfe347b9c82
Create Date: 2021-10-29 21:11:28.273129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a3fe14c17b2'
down_revision = 'bdfe347b9c82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application_user', sa.Column('date_of_birth', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('application_user', 'date_of_birth')
    # ### end Alembic commands ###
