"""Role column added

Revision ID: 4800ad5bfcc6
Revises: 3a3fe14c17b2
Create Date: 2021-10-31 13:01:13.315614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4800ad5bfcc6'
down_revision = '3a3fe14c17b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application_user', sa.Column('role', sa.Enum('ADMIN', 'USER', name='roles'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('application_user', 'role')
    # ### end Alembic commands ###
