"""Feed table created

Revision ID: 82713fd7412e
Revises: 01d5a3667eed
Create Date: 2021-11-11 00:01:42.989002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82713fd7412e'
down_revision = '01d5a3667eed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feed',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_timestamp', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('last_modified_timestamp', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('reference_code', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('published', sa.Boolean(), nullable=True),
    sa.Column('application_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['application_user_id'], ['application_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference_code')
    )
    op.create_index(op.f('ix_feed_id'), 'feed', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feed_id'), table_name='feed')
    op.drop_table('feed')
    # ### end Alembic commands ###
