"""Initial migration

Revision ID: bc3b1fb31cae
Revises: 
Create Date: 2021-11-05 20:55:22.337183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc3b1fb31cae'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application_user',
    sa.Column('created_timestamp', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('last_modified_timestamp', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('reference_code', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'USER', name='roles'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference_code')
    )
    op.create_index(op.f('ix_application_user_email'), 'application_user', ['email'], unique=True)
    op.create_index(op.f('ix_application_user_id'), 'application_user', ['id'], unique=False)
    op.create_index(op.f('ix_application_user_username'), 'application_user', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_application_user_username'), table_name='application_user')
    op.drop_index(op.f('ix_application_user_id'), table_name='application_user')
    op.drop_index(op.f('ix_application_user_email'), table_name='application_user')
    op.drop_table('application_user')
    # ### end Alembic commands ###
