"""Create application_user table

Revision ID: bdfe347b9c82
Revises: 
Create Date: 2021-10-29 20:34:20.157408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdfe347b9c82'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_application_user_email'), 'application_user', ['email'], unique=True)
    op.create_index(op.f('ix_application_user_id'), 'application_user', ['id'], unique=False)
    op.create_index(op.f('ix_application_user_username'), 'application_user', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_application_user_username'), table_name='application_user')
    op.drop_index(op.f('ix_application_user_id'), table_name='application_user')
    op.drop_index(op.f('ix_application_user_email'), table_name='application_user')
    op.drop_table('application_user')
    # ### end Alembic commands ###
